name: citation_grapher_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - wheel
  - pip:
    - bibtexparser==1.4.0
    - matplotlib==3.6.1
    - networkx==2.8.7
    - numpy==1.23.3
    - openpyxl==3.0.10
    - pandas==1.5.0
    - pyvis==0.3.0
    - ratelimit==2.2.1
    - requests==2.28.1
    - seaborn==0.12.0
    - thefuzz==0.19.0
    - tqdm==4.64.1
    - wasabi==0.10.1